name: metacentrum_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - async-lru
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - bleach
  - brotli
  - certifi
  - cffi
  - charset-normalizer
  - click
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - distlib
  - docker-pycreds
  - exceptiongroup
  - executing
  - fastjsonschema
  - filelock
  - fonttools
  - gitdb
  - gitpython
  - gmpy2
  - idna
  - importlib-metadata
  - importlib-resources
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter-events
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab-pygments
  - jupyterlab_server
  - kiwisolver
  - markupsafe
  - matplotlib
  - matplotlib-inline
  - mistune
  - mpmath
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - notebook-shim
  - numpy
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pbr
  - pexpect
  - pickleshare
  - pillow
  - pkgutil_resolve_name
  - platformdirs
  - pooch
  - prometheus-client
  - prompt-toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pure-eval
  - pycparser
  - pygments
  - pyparsing
  - pysocks
  - python-dateutil
  - python-dotenv
  - python-json-logger
  - pytz
  - pyyaml
  - pyzmq
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - scipy
  - seaborn
  - send2trash
  - sentry-sdk
  - setproctitle
  - six
  - smmap
  - sniffio
  - soupsieve
  - stack-data
  - stevedore
  - sympy
  - terminado
  - tinycss2
  - tomli
  - torch
  - torchaudio
  - torchsummary
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - types-tqdm
  - typing-extensions
  - tzdata
  - urllib3
  - virtualenv
  - virtualenv-clone
  - virtualenvwrapper
  - wandb
  - wcwidth
  - webencodings
  - websocket-client
  - zipp
